feat: adds action items to navbar (header)
rsksmart/rif-ui pull request #182
Opened 2020-11-01 15:37 UTC by jurajpiar

Adds additional items to the header
Refactor- uses grid for layout

Resolves [RMKT-349](https://rsklabs.atlassian.net/browse/RMKT-349)

2020-11-03 14:56 UTC, farinalvaro requested changes
Just commented about a compiling error and a mix between `item` and `container` props of Grid component. Apart from that, looks great!

2020-11-03 14:56 UTC, farinalvaro commented on src/components/organisms/Header/HeaderDesktop.tsx
> +          >
I think `container` prop of `Grid` component should not be mixed with `item` prop. Items should be wrapped inside containers

2020-11-03 14:56 UTC, farinalvaro commented on src/components/organisms/Header/HeaderDesktop.tsx
> +          >
Same comment about items and containers

2020-11-03 14:56 UTC, farinalvaro commented on src/components/organisms/Header/HeaderMobile.tsx
> +                alignContent="center"
Same comment about items and containers

2020-11-03 14:56 UTC, farinalvaro commented on src/components/organisms/Header/HeaderDesktop.tsx
> +              <ListItemIcon key={icon.key} {...{ onClick }}>
Got this error compiling: 
```Type 'string | number | null' is not assignable to type 'string | number | undefined'.```

2020-11-03 14:56 UTC, farinalvaro commented on src/components/organisms/Header/HeaderDesktop.tsx
> +            alignContent="center"
Same comment about items and containers

2020-11-07 12:19 UTC, jurajpiar commented on src/components/organisms/Header/HeaderDesktop.tsx
> +              <ListItemIcon key={icon.key} {...{ onClick }}>
no longer an issue

2020-11-09 17:33 UTC, farinalvaro approved these changes
🎉

2020-11-09 17:34 UTC, merged